### ISSUE TITLE
App crashes when just pressing add record when creating a problem

### ISSUE THREAD

**Issue by tcchan97** [CMPUT301F18T01/MDBook#79] opened 2018-11-29 09:44 UTC
App crashes when just pressing the add record button and leaving everything empty in adding a problem

**Comment by haondt** [comment] 2018-11-29 22:21
is this in the master branch?

**Comment by Vanessa0122** [comment] 2018-11-30 00:44
US 01.05.01
"As a patient I want to add records (photos, locations, comments) to problems."
We should make sure the problem is created before the user is adding a record to the problem, so we are deleting the button in the AddProblemActivity.

**Comment by haondt** [comment] 2018-11-30 00:54
@Vanessa0122 I just want to confirm this issue is resolved, as per your comment [here](https://github.com/CMPUT301F18T01/MDBook/issues/66#issuecomment-443049795)? If so can you mention which commit/pull request/branch it was solved in and close this issue?

**Comment by Vanessa0122** [comment] 2018-11-30 22:44
CLOSING NOTE: User is not allowed to add record before a problem is added to the database. Button removed, issue solved.

**Closed by Vanessa0122** 2018-11-30 22:44 UTC
